NULL = "null"
OUT_OF_DATE_RANGE = "out of date range"
OUT_OF_DATETIME_RANGE = "out of datetime range"
OUT_OF_DATETIME2_RANGE = "out of datetime2 range"
EMPTY_SET = "empty set"
COLS_BITMAP = "cols bitmap"
JSON_PARTIAL_UPDATE = "same with before values"
